run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tests
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/sciffer/agentbox
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - goconst
    - gocyclo
    - lll

issues:
  exclude-rules:
    # Exclude some linters from generated files
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
    # Exclude known linter issues in test files
    - text: "Error return value of .* is not checked"
      path: _test\.go
    - text: "unused"
      path: _test\.go
  max-issues-per-linter: 0
  max-same-issues: 0
