run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - unnamedResult
      - paramTypeCombine
      - rangeValCopy
  gocyclo:
    min-complexity: 25
  misspell:
    locale: US
  lll:
    line-length: 160
  goimports:
    local-prefixes: github.com/sciffer/agentbox
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - goconst
    - gocyclo
    - lll

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
        - unused
        - gocritic
    # Exclude known linter issues in test files
    - text: "Error return value of .* is not checked"
      path: _test\.go
    - text: "unused"
      path: _test\.go
    - text: "var.*is unused"
      path: _test\.go
    # Allow stuttering for handler types
    - text: "stutters"
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
